apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.6
          env:
            - name: REGISTRY_HTTP_ADDR
              value: ":5000"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: image-store
              mountPath: "/var/lib/registry"
      volumes:
        - name: image-store
          emptyDir: {}
      
--- 
  apiVersion: v1
  kind: Service
  metadata:
    name: registry-svc
  spec:
    type: NodePort
    selector:
      app: registry
    ports:
      - port: 5000
        nodePort: 30500
        protocol: TCP