apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: zookeeper
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
---
  apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
    labels:
      app: kafka
      component: zookeeper
  spec:
    ports:
    - port: 2181
      name: zookeeper-port
      targetPort: 2181
      protocol: TCP
    selector:
      app: kafka
      component: zookeeper