apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-data-service-deployment
  labels:
    app: search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: kubernetes.docker.internal:30500/search/data-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:  
    name: search-data-service-svc
  spec:
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
    selector: 
      app: search
